name: CI
on:
  push:
    branches:
      - develop

jobs:
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    environment: develop
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.2.0
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm test
      - name: Lint
        run: npm run lint
      - name: AddOn
        run: |
          echo ${API_DOMAIN}
